apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rails-app-pipeline
spec:
  params:
    - name: repo-url
      type: string
      description: The git repo URL to clone from
    - name: image-name
      type: string
      description: The name of the image to build
    - name: dockerhub-username
      type: string
      description: Docker Hub username
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "$(params.repo-url)"
        - name: deleteExisting
          value: "true"
    - name: build-and-push
      taskRef:
        name: kaniko
      runAfter:
        - fetch-source
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: "$(params.dockerhub-username)/$(params.image-name):latest"