# tekton-pipelinerun.yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: rails-app-pipelinerun-
spec:
  pipelineRef:
    name: rails-app-pipeline
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
    - name: source-repo
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
    - name: dockerconfig
      secret:
        secretName: dockerhub-creds
        items:
          - key: .dockerconfigjson
            path: config.json