# tekton-pipeline.yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rails-app-pipeline
spec:
  params:
    - name: image-name
      type: string
      default: "rails-app"
  workspaces:
    - name: source-repo
    - name: dockerconfig
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source-repo
      params:
        - name: url
          value: "https://github.com/raima3006/rails-app-gitops.git"
    - name: build-and-push
      taskRef:
        name: kaniko
      runAfter: ["fetch-source"]
      workspaces:
        - name: source
          workspace: source-repo
        - name: dockerconfig
          workspace: dockerconfig
      params:
        - name: IMAGE
          value: "raima01/$(params.image-name):latest"