default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: rails_app_development

test:
  <<: *default
  database: rails_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  host: postgres
  username: postgres
  password: password
  database: rails_app_production

  # SolidCache requires this exact configuration key
  cache:
    <<: *default
    database: rails_app_cache
    migrations_paths: db/cache_migrate

cable:
  <<: *default
  database: rails_app_production

queue:
  <<: *default
  database: rails_app_production