apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rails-app
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/your-username/rails-app-gitops.git
    path: kubernetes/
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true